<h2>TFSA-2021-127: Division by 0 in <code>ResourceGather</code></h2>
<h3>CVE Number</h3>
<p>CVE-2021-37653</p>
<h3>Impact</h3>
<p>An attacker can trigger a crash via a floating point exception in
<code>tf.raw_ops.ResourceGather</code>:</p>
<p>```python
import tensorflow as tf</p>
<p>tensor = tf.constant(value=[[]],shape=(0,1),dtype=tf.uint32)
v = tf.Variable(tensor)
tf.raw_ops.ResourceGather(
    resource=v.handle,
    indices=[0],
    dtype=tf.uint32,
    batch_dims=1,
    validate_indices=False)
```</p>
<p>The
<a href="https://github.com/tensorflow/tensorflow/blob/f24faa153ad31a4b51578f8181d3aaab77a1ddeb/tensorflow/core/kernels/resource_variable_ops.cc#L725-L731">implementation</a>
computes the value of a value, <code>batch_size</code>, and then divides by it without
checking that this value is not 0.</p>
<h3>Patches</h3>
<p>We have patched the issue in GitHub commit
<a href="https://github.com/tensorflow/tensorflow/commit/ac117ee8a8ea57b73d34665cdf00ef3303bc0b11">ac117ee8a8ea57b73d34665cdf00ef3303bc0b11</a>.</p>
<p>The fix will be included in TensorFlow 2.6.0. We will also cherrypick this
commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are
also affected and still in supported range.</p>
<h3>For more information</h3>
<p>Please consult <a href="https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md">our security
guide</a> for
more information regarding the security model and how to contact us with issues
and questions.</p>
<h3>Attribution</h3>
<p>This vulnerability has been reported by members of the Aivul Team from Qihoo
360.</p>